// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuUt2SVOow24djiW_Xo0FBkUtzhFagt6U',
    appId: '1:50531703118:web:6b1d2ccaf9e7da3a21661f',
    messagingSenderId: '50531703118',
    projectId: 'chit-chat-app-9e22a',
    authDomain: 'chit-chat-app-9e22a.firebaseapp.com',
    storageBucket: 'chit-chat-app-9e22a.firebasestorage.app',
    measurementId: 'G-7QLWJXFQCM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4SopN0kAUYa1upWamidk8FQK619lnRqM',
    appId: '1:50531703118:android:7181cd73a14d9cd521661f',
    messagingSenderId: '50531703118',
    projectId: 'chit-chat-app-9e22a',
    storageBucket: 'chit-chat-app-9e22a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjY8pQdOVayVqvkz5UZm0qhjLfGW2dyE8',
    appId: '1:50531703118:ios:08a79d1d5123b6fc21661f',
    messagingSenderId: '50531703118',
    projectId: 'chit-chat-app-9e22a',
    storageBucket: 'chit-chat-app-9e22a.firebasestorage.app',
    iosBundleId: 'com.example.chitchat',
  );
}
